### PR TITLE
Add more public API features

### LINKED ISSUE #151: [FEATURE] Support more public API and swift-calls
### Feature you want to implement
I want to add some necessary APIs:
1. Get the current appinfos.
2. Get the current channel subscription of an app.
3. Change the channel subscription of an app.
... and what more do we need?

### How the feature is implemented
In a straightforward way!

### PR DESCRIPTION
**Pull request by kangz12345**
New features:
- `appNames()`: All the names of the existing apps
- `channelNames()`: All the names of the existing channels
- `subscriberNames(channel)`: All the subscriber app names of the channel
- `subscribe(app, channel)`: The app subscribes to the channel
- `unsubscribe(app, channel)`: The app unsubscribes from the channel

This closes #151.

### CODE REVIEW

**Comment by BECATRUE** [comment]
Wow! `TODO` causes a Pylint warning, but I think it doesn't matter.

**Review by BECATRUE — APPROVED** [review]
It looks so good!

**Comment by kangz12345** [comment]
@BECATRUE Please approve this again, since I modified the code to remove the pylint warning.

**Review by BECATRUE — APPROVED** [review]
So good!

**Pull request merged**
